### ISSUE TITLE
Make a blog site for Vita

### ISSUE THREAD

**Issue by Lalit3716** [Vita-App/Blog#1]
### Description

We would like to have a blog site for the Vita app for writing technical blogs expressing the journey of the project!

This would be hosted on a different subdomain like `blog.vita.com`

Example : https://blog.adplist.org/

- Discussion on which headless CMS to use & why (Gatsby, Ghost, Strapi, Netlify, WordPress, etc)
- It should be cheap (ideally free)
- I should be easily integrated with React
- Adding blogs should be as easily as this would be managed by non-technical people

### Domain

Front-End (Styling/Markup)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE%20OF%20CONDUCT.md) of this project.

**Comment by Senor-Ducky** [comment]
I would like to take this up
